name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK & Gradle
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk wget unzip

          # تحميل وتثبيت Gradle
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip
          echo "export PATH=$PWD/gradle-7.5/bin:$PATH" >> $GITHUB_ENV

          # تحميل Android SDK
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          # ضبط متغيرات البيئة
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Licenses & Install Build Tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
