name: Build APK Without Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # استخدام إصدار مستقر

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Package Lists
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -y || true
          sleep 5  # تجنب مشاكل الشبكة
          sudo apt-get install -y wget unzip openjdk-11-jdk

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-*.zip -d android-sdk
          yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk "platforms;android-30" "build-tools;30.0.3"

      - name: Compile Java Files
        run: |
          mkdir -p bin
          javac -d bin -source 8 -target 8 $(find src -name "*.java")

      - name: Convert Class Files to DEX
        run: |
          android-sdk/build-tools/30.0.3/d8 --output=bin/classes.dex $(find bin -name "*.class")

      - name: Create APK Structure
        run: |
          mkdir -p build/apk
          cp -r res build/apk/
          cp AndroidManifest.xml build/apk/
          android-sdk/build-tools/30.0.3/aapt package -f -m -J src -M build/apk/AndroidManifest.xml -S res -I android-sdk/platforms/android-30/android.jar
          android-sdk/build-tools/30.0.3/aapt package -f -F build/app_unsigned.apk -M build/apk/AndroidManifest.xml -S res -I android-sdk/platforms/android-30/android.jar

      - name: Sign APK
        run: |
          android-sdk/build-tools/30.0.3/apksigner sign --ks my-release-key.jks --ks-key-alias my-key-alias --out build/app_signed.apk build/app_unsigned.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/app_signed.apk
