name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK & Gradle
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk wget unzip
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip
          export PATH=$PWD/gradle-7.5/bin:$PATH
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d android-sdk
          export ANDROID_SDK_ROOT=$PWD/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.1"

      - name: Build APK
        run: |
          cd app
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/debug/*.apk
