name: Build APK

on:
  push:
    branches:
      - main  # يمكنك تعديل هذا إلى الفرع الذي تستخدمه

jobs:
  build:
    runs-on: ubuntu-latest  # أو يمكنك اختيار نظام تشغيل آخر

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease
